import type { LevelConfig } from "../types/Level";

export const LEVEL_CONFIGS: LevelConfig[] = [
  {
    level: 1,
    name: "Enchanted Forest",
    duration: 60,
    spawnInterval: 1.5,
    enemyHealthMultiplier: 1,
    enemySpeedMultiplier: 1,
  },
  {
    level: 2,
    name: "Dark Forest",
    duration: 60,
    spawnInterval: 1.35,
    enemyHealthMultiplier: 1.2,
    enemySpeedMultiplier: 1.05,
  },
  {
    level: 3,
    name: "Forgotten Ruins",
    duration: 60,
    spawnInterval: 1.2,
    enemyHealthMultiplier: 1.4,
    enemySpeedMultiplier: 1.1,
  },
  {
    level: 4,
    name: "Cursed Swamp",
    duration: 60,
    spawnInterval: 1.1,
    enemyHealthMultiplier: 1.6,
    enemySpeedMultiplier: 1.15,
  },
  {
    level: 5,
    name: "Demon Cemetery",
    duration: 60,
    spawnInterval: 1.0,
    enemyHealthMultiplier: 1.8,
    enemySpeedMultiplier: 1.2,
  },
  {
    level: 6,
    name: "Burning Valley",
    duration: 60,
    spawnInterval: 0.9,
    enemyHealthMultiplier: 2.1,
    enemySpeedMultiplier: 1.25,
  },
  {
    level: 7,
    name: "Abyss Gate",
    duration: 60,
    spawnInterval: 0.8,
    enemyHealthMultiplier: 2.4,
    enemySpeedMultiplier: 1.3,
  },
  {
    level: 8,
    name: "Infernal Castle",
    duration: 60,
    spawnInterval: 0.7,
    enemyHealthMultiplier: 2.7,
    enemySpeedMultiplier: 1.35,
  },
  {
    level: 9,
    name: "Demon Realm",
    duration: 60,
    spawnInterval: 0.6,
    enemyHealthMultiplier: 3.0,
    enemySpeedMultiplier: 1.4,
  },
  {
    level: 10,
    name: "Hell Throne",
    duration: 60,
    spawnInterval: 0.5,
    enemyHealthMultiplier: 3.5,
    enemySpeedMultiplier: 1.5,
  },
];